version: 2
jobs:
 base-build:
   machine: true
   steps:
     - checkout
     - run:
           name: Build Base Container
           command: |
            docker build -f Dockerfile.base -t ecohealthalliance/reservoir .
 base-deploy:
   machine: true
   steps:
     - deploy:
           name: Push to Docker Hub
           command: |
              docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
              docker push ecohealthalliance/reservoir
 gpu-build:
   machine: true
   steps:
     - checkout
     - run:
           name: Build GPU Container
           command: |
            docker build -f Dockerfile.gpu -t ecohealthalliance/reservoir:gpu .
 gpu-deploy:
   machine: true
   steps:
     - deploy:
           name: Push to Docker Hub
           command: |
              docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
              docker push ecohealthalliance/reservoir:gpu

workflows:
   version: 2
   commit:
     jobs:
       - base-build
       - gpu-build
       - base-deploy:
           requires:
             - base-build
           filters:
             branches:
               only:
                 - master
       - gpu-deploy:
           requires:
             - gpu-build
           filters:
             branches:
               only:
                 - master
  weekly:
    triggers:
      - schedule:
          cron: "0 10 * * 0"
          filters:
            branches:
              only:
                - master
     jobs:
       - base-build
       - gpu-build
       - base-deploy:
           requires:
             - base-build
       - gpu-deploy:
           requires:
             - gpu-build
