version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     - run:
           name: Build Container
           command: |
            docker build -t ecohealthalliance/reservoir .
     - deploy:
           name: Push to Docker Hub
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push ecohealthalliance/reservoir
              fi
              
workflows:
   version: 2
   commit:
     jobs:
       - build
   nightly:
     triggers:
       - schedule:
           cron: "0 0 * * *"
           filters:
             branches:
               only:
                 - master
     jobs:
       - build
