version: 2
jobs:
 base:
   machine: true
   steps:
     - checkout
     - run:
           name: Build Base Container
           command: |
            docker build -f Dockerfile.base -t ecohealthalliance/reservoir .
     - deploy:
           name: Push to Docker Hub
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push ecohealthalliance/reservoir
              fi
 gpu:
   machine: true
   steps:
     - checkout
     - run:
           name: Build GPU Container
           command: |
            docker build -f Dockerfile.gpu -t ecohealthalliance/reservoir:gpu .
     - deploy:
           name: Push to Docker Hub
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASS
                docker push ecohealthalliance/reservoir:gpu
              fi
              
workflows:
   version: 2
   commit:
     jobs:
       - base
       - gpu
